version: "3.9"

services:
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: ../infra/frontend.Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://localhost:4000
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/backend.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000

  model:
    build:
      context: ../model
      dockerfile: ../infra/model.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_ENV=production
